// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFWt6cJeagLMdR4f32xKML5G75NjDsm9s',
    appId: '1:615254432241:web:440e6aafed7cda7342cc50',
    messagingSenderId: '615254432241',
    projectId: 'flutterchatapp-cybersoft',
    authDomain: 'flutterchatapp-cybersoft.firebaseapp.com',
    storageBucket: 'flutterchatapp-cybersoft.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-upQemhVkooYVhLFgNsrhuDmsU-KnoaI',
    appId: '1:615254432241:android:823a3f46691123b742cc50',
    messagingSenderId: '615254432241',
    projectId: 'flutterchatapp-cybersoft',
    storageBucket: 'flutterchatapp-cybersoft.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1ADD0e5JL4uKLkaDBpQXLITgITEB5lec',
    appId: '1:615254432241:ios:cfc5c61a96fb5b9b42cc50',
    messagingSenderId: '615254432241',
    projectId: 'flutterchatapp-cybersoft',
    storageBucket: 'flutterchatapp-cybersoft.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1ADD0e5JL4uKLkaDBpQXLITgITEB5lec',
    appId: '1:615254432241:ios:cfc5c61a96fb5b9b42cc50',
    messagingSenderId: '615254432241',
    projectId: 'flutterchatapp-cybersoft',
    storageBucket: 'flutterchatapp-cybersoft.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFWt6cJeagLMdR4f32xKML5G75NjDsm9s',
    appId: '1:615254432241:web:07fccb6cbe22bafa42cc50',
    messagingSenderId: '615254432241',
    projectId: 'flutterchatapp-cybersoft',
    authDomain: 'flutterchatapp-cybersoft.firebaseapp.com',
    storageBucket: 'flutterchatapp-cybersoft.firebasestorage.app',
  );
}


// ! HƯỚNG DẪN KẾT NỐI FLUTTER VỚI FIREBASE
// * Bước 1: Cài đặt FlutterFire CLI
// - Đảm bảo đã cài đặt Node.js và Yarn.
// - Cài đặt Firebase CLI và FlutterFire CLI:
//   ```bash
//   yarn global add firebase-tools
//   dart pub global activate flutterfire_cli
//   ```
// - Thêm FlutterFire CLI vào PATH (nếu cần):
//   ```bash
//   echo 'export PATH="$PATH:$HOME/.pub-cache/bin"' >> ~/.zshrc
//   source ~/.zshrc
//   ```
// - Kiểm tra phiên bản:
//   ```bash
//   flutterfire --version
//   ```

// * Bước 2: Cấu hình Firebase trong dự án
// - Di chuyển vào thư mục dự án:
//   ```bash
//   cd flutter_chat_app
//   ```
// - Chạy lệnh cấu hình:
//   ```bash
//   flutterfire configure
//   ```
// - Chọn Firebase project và các nền tảng hỗ trợ (Android, iOS, macOS, web, hoặc Windows).
// - Nhập Android package name (ví dụ: com.example.flutter_chat_app).
// - Nếu gặp lỗi:
//   - Package name không đúng: Mở `android/app/src/main/AndroidManifest.xml` để kiểm tra thuộc tính `package`.
//   - Firebase app chưa được cấu hình trên Firebase Console: Thêm thủ công từ Firebase Console.

// * Bước 3: Kiểm tra tệp cấu hình
// - Sau khi cấu hình, tệp Firebase options được tạo tại:
//   ```
//   lib/firebase_options.dart
//   ```

// * Bước 4: Cài đặt Firebase SDK
// - Thêm các gói Firebase cần thiết vào `pubspec.yaml`:
//   ```yaml
//   dependencies:
//     firebase_core: ^2.5.2
//     firebase_auth: ^4.4.0
//     cloud_firestore: ^5.3.0
//   ```
// - Chạy:
//   ```bash
//   flutter pub get
//   ```

// * Bước 5: Khởi tạo Firebase trong Flutter
// - Thêm đoạn mã khởi tạo Firebase trong `main.dart`:
// import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart';

// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//   await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
//   );
//   runApp(MyApp());
// }

// class MyApp extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       home: Scaffold(
//         appBar: AppBar(title: Text('Flutter with Firebase')),
//         body: Center(child: Text('Firebase Configured')),
//       ),
//     );
//   }
// }

// * Bước 6: Cấu hình riêng cho từng nền tảng
// - Android:
//   - Kiểm tra `android/app/src/main/AndroidManifest.xml` để đảm bảo `package` chính xác.
//   - Thêm SHA-1/SHA-256 trong Firebase Console nếu sử dụng Authentication.
// - iOS:
//   - Cài CocoaPods nếu chưa:
//     ```bash
//     sudo gem install cocoapods
//     ```
//   - Chạy lệnh:
//     ```bash
//     cd ios
//     pod install
//     ```

// * Bước 7: Kiểm tra kết nối
// - Chạy ứng dụng Flutter:
//   ```bash
//   flutter run
//   ```
// - Đảm bảo không có lỗi Firebase trong terminal.

// ! Lỗi thường gặp và cách xử lý:
// - "Package name cannot be empty":
//   - Xem lại giá trị `package` trong `AndroidManifest.xml`.
// - "Firebase app is not registered":
//   - Kiểm tra xem ứng dụng đã được thêm vào Firebase Console hay chưa.
// - `flutterfire configure` không nhận diện dự án Flutter:
//   - Đảm bảo bạn đang ở trong thư mục dự án Flutter trước khi chạy lệnh.

// ? Tài liệu tham khảo:
// - [Firebase Flutter Setup](https://firebase.google.com/docs/flutter/setup)
// - [FlutterFire CLI Documentation](https://firebase.google.com/docs/flutter/setup?platform=cli)
